## Dockerfile-dev
FROM openjdk:19-alpine
EXPOSE 8080
ARG JAR_FILE=/build/libs/grandchild-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","-Dspring.profiles.active=dev","/app.jar"]